from __future__ import annotations


SAMPLE_RECIPES: list[dict] = [
    {
        "id": "bun-bo-hue",
        "name": "Bún Bò Huế",
        "description": "Spicy beef noodle soup with lemongrass and rich broth.",
        "image": "/image/Food/BunBoHue.jpg",
        "ingredients": ["beef", "rice noodles", "lemongrass", "chili", "fish sauce", "shallot"],
        "steps": [
            "Simmer beef bones with lemongrass to build the broth.",
            "Season with fish sauce, chili, and aromatics.",
            "Add noodles, sliced beef, and herbs before serving.",
        ],
        "taste_tags": ["spicy", "savory"],
        "diet_tags": ["high-protein"],
        "time_minutes": 45,
        "nutrition": {"calories": 480, "protein": 29, "carbs": 52, "fat": 16},
    },
    {
        "id": "com-tam-suon",
        "name": "Cơm Tấm Sườn",
        "description": "Broken rice with grilled pork chop, egg, and pickled vegetables.",
        "image": "/image/Food/ComTamSuon.png",
        "ingredients": ["pork", "rice", "egg", "cucumber", "pickled vegetables", "fish sauce"],
        "steps": [
            "Marinate pork chops with garlic, fish sauce, and sugar.",
            "Grill the pork and fry the egg.",
            "Serve over rice with vegetables and sauce.",
        ],
        "taste_tags": ["savory", "grilled"],
        "diet_tags": ["balanced"],
        "time_minutes": 35,
        "nutrition": {"calories": 520, "protein": 31, "carbs": 56, "fat": 18},
    },
    {
        "id": "banh-xeo",
        "name": "Bánh Xèo",
        "description": "Crispy Vietnamese sizzling pancake with shrimp and bean sprouts.",
        "image": "/image/Food/BanhXeo.jpg",
        "ingredients": ["rice flour", "shrimp", "bean sprouts", "coconut milk", "turmeric", "lettuce"],
        "steps": [
            "Mix batter with rice flour, coconut milk, and turmeric.",
            "Pan-fry with shrimp and bean sprouts until crisp.",
            "Serve with lettuce and dipping sauce.",
        ],
        "taste_tags": ["crispy", "savory"],
        "diet_tags": ["quick"],
        "time_minutes": 30,
        "nutrition": {"calories": 340, "protein": 14, "carbs": 41, "fat": 12},
    },
    {
        "id": "goi-ga-healthy",
        "name": "Gỏi Gà Rau Củ",
        "description": "Light chicken salad with fresh herbs and a citrus dressing.",
        "image": "/image/Food/VegetableDish.png",
        "ingredients": ["chicken", "cabbage", "carrot", "mint", "lime", "peanut"],
        "steps": [
            "Shred cooked chicken and slice vegetables thinly.",
            "Toss everything with lime dressing and herbs.",
            "Top with peanuts before serving.",
        ],
        "taste_tags": ["fresh", "light"],
        "diet_tags": ["healthy", "high-protein"],
        "time_minutes": 20,
        "nutrition": {"calories": 260, "protein": 24, "carbs": 18, "fat": 10},
    },
    {
        "id": "com-chien-trung",
        "name": "Cơm Chiên Trứng",
        "description": "Quick fried rice with egg, vegetables, and soy sauce.",
        "image": "/image/Food/VegetableDish.png",
        "ingredients": ["rice", "egg", "carrot", "green peas", "soy sauce", "spring onion"],
        "steps": [
            "Scramble eggs, then stir-fry vegetables.",
            "Add rice and soy sauce, then toss until evenly coated.",
            "Finish with spring onion and serve hot.",
        ],
        "taste_tags": ["savory", "quick"],
        "diet_tags": ["budget", "quick"],
        "time_minutes": 15,
        "nutrition": {"calories": 390, "protein": 13, "carbs": 56, "fat": 11},
    },
    {
        "id": "dau-hu-sot-ca-chua",
        "name": "Đậu Hũ Sốt Cà Chua",
        "description": "Simple vegetarian tofu dish in a tomato sauce.",
        "image": "/image/Food/VegetableDish.png",
        "ingredients": ["tofu", "tomato", "garlic", "spring onion", "soy sauce", "oil"],
        "steps": [
            "Pan-fry the tofu until lightly golden.",
            "Cook tomato sauce with garlic and soy sauce.",
            "Simmer tofu in sauce and serve with rice.",
        ],
        "taste_tags": ["savory", "light"],
        "diet_tags": ["vegetarian", "healthy", "budget"],
        "time_minutes": 25,
        "nutrition": {"calories": 240, "protein": 16, "carbs": 14, "fat": 12},
    },
]
